// <auto-generated />
namespace ASP_Video_Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class MediaFile_changes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MediaFile_changes));
        
        string IMigrationMetadata.Id
        {
            get { return "201505042205168_MediaFile_changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
